"""
Django settings for test_project project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'p6+yp$apq_%m^w!ty_2cj)!b#u+xkg%lb-t76q@)1#zt3+)s4s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['.example.com',]
#EMAIL_BACKEND = 'django_ses.SESBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'educamp2409@gmail.com'
EMAIL_HOST_PASSWORD ='roaring40s'
#EMAIL_TIMEOUT = 300
#SERVER_EMAIL = EMAIL_HOST_USER
EMAIL_PORT = 587
EMAIL_USE_TLS = True


DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# Application definition

INSTALLED_APPS = (
    #django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_ses',

    #third party apps
    'crispy_forms',
    'registration',
    'haystack',
    'whoosh',
    'bs4',
    #my apps
    'newsletter',
    'eduplus',
    'mentor',
    'feedback',
    'chat',
    'extension',
    'institution',
    'dynamic_scraper',
    'djcelery',
    'open_news',
    'scrapy',
    'map',
    'social.apps.django_app.default'



)

HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
        'PATH': os.path.join(os.path.dirname(__file__), 'whoosh_index'),
    },
}

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'social.apps.django_app.middleware.SocialAuthExceptionMiddleware',
)
AUTHENTICATION_BACKENDS = (
    'social.backends.google.GoogleOAuth2',
    'social.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
    #'social.backends.twitter.TwitterOAuth',
    #'django.contrib.auth.backends.ModelBackend'
    )

ROOT_URLCONF = 'test_project.urls'

SOCIAL_AUTH_FACEBOOK_KEY = '631999380271652'
SOCIAL_AUTH_FACEBOOK_SECRET = '35fa7b9329b1c40177d64edc41fff133'
TEMPLATE_CONTEXT_PROCESSORS = (
   'django.contrib.auth.context_processors.auth',
   'django.core.context_processors.debug',
   'django.core.context_processors.i18n',
   'django.core.context_processors.media',
   'django.core.context_processors.static',
   'django.core.context_processors.tz',
   'django.contrib.messages.context_processors.messages',
   'social.apps.django_app.context_processors.backends',
   'social.apps.django_app.context_processors.login_redirect',
)


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'test_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'educamp',
        'USER': 'root',
        'PASSWORD': 'darkknight',
        #'HOST':'',
        #'PORT':'',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT =  os.path.join(os.path.dirname(BASE_DIR), "static_in_env", 'static_root')



STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static_in_pro", "our_static"),
   # os.path.join(BASE_DIR, "static_in_env"),
   # '/var/www/static/',
)
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = "1071089890909-k22ve5ugsleo2olak1q5e80pefb24rup"
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = "08q4g-IwJOu3cI6knVkF49vI"

MEDIA_URL ='/media/'

#MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static_in_env", 'media_root')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



#registration-redux
ACCOUNT_ACTIVATION_DAYS = 7
REGISTRATION_AUTO_LOGIN = True
SITE_ID = 1
LOGIN_REDIRECT_URL ='/profile/'


#crispy form
CRISPY_TEMPLATE_PACK = 'bootstrap3'
